#!/bin/bash

# Demo script to show the new pure ASCII UI

echo "======================================================================="
echo "            PURE ASCII POKER UI DEMONSTRATION"
echo "======================================================================="
echo ""
echo "This is what the game interface looks like with pure ASCII characters."
echo ""
echo "========================================================================"
echo "                      TEXAS HOLD'EM POKER                            "
echo "========================================================================"
echo " POT: 150        chips | CURRENT BET: 50       | ROUND: turn          "
echo "========================================================================"
echo ""
echo "----------------------------------------------------------------------"
echo "                        COMMUNITY CARDS                              "
echo "----------------------------------------------------------------------"
echo "  [AS] [KH] [QD] [JC] [??]"
echo "----------------------------------------------------------------------"
echo ""
echo "----------------------------------------------------------------------"
echo "                            PLAYERS                                  "
echo "----------------------------------------------------------------------"
echo ">>> Alice           [DEALER]  [*TURN*]  Chips: 950     Bet: 50      <YOU>"
echo "    Bob                                 Chips: 900     Bet: 50     "
echo "    Charlie                             Chips: 800                  [FOLDED]"
echo "----------------------------------------------------------------------"
echo ""
echo "----------------------------------------------------------------------"
echo "                          YOUR HAND                                  "
echo "----------------------------------------------------------------------"
echo "                         [TH] [9H]                                   "
echo "----------------------------------------------------------------------"
echo "  Your Chips: 950       |  Your Bet This Round: 50                  "
echo "----------------------------------------------------------------------"
echo ""
echo "======================================================================"
echo "                         *** YOUR TURN! ***                          "
echo "======================================================================"
echo "  fold       - Fold your hand and forfeit this round"
echo "  call       - Call 0 chips to match current bet"
echo "  raise X    - Raise the bet (minimum: 100 chips)"
echo "======================================================================"
echo ""
echo "Commands: fold | check | call | raise <amount> | chat <message> | help | quit"
echo "> "
echo ""
echo "======================================================================="
echo "KEY FEATURES:"
echo "  - Pure ASCII characters (=, -, |) for compatibility"
echo "  - Clear section headers and separators"
echo "  - >>> marker to quickly find yourself"
echo "  - [DEALER], [*TURN*], <YOU> labels are easy to spot"
echo "  - Card format: [AS] [KH] simple and readable"
echo "  - No Unicode required - works on ANY terminal"
echo "======================================================================="
